CREATE TABLE `similarity_st` (
  `id` int NOT NULL,
  `translate_chn` decimal(10,5) DEFAULT NULL,
  `translate_my` decimal(10,5) DEFAULT NULL,
  `translate_tm` decimal(10,5) DEFAULT NULL,
  `cm_en_chn` decimal(10,5) DEFAULT NULL,
  `cm_en_my` decimal(10,5) DEFAULT NULL,
  `cm_en_tm` decimal(10,5) DEFAULT NULL,
  `cm_chn_en` decimal(10,5) DEFAULT NULL,
  `cm_chn_my` decimal(10,5) DEFAULT NULL,
  `cm_chn_tm` decimal(10,5) DEFAULT NULL,
  `cm_my_en` decimal(10,5) DEFAULT NULL,
  `cm_my_chn` decimal(10,5) DEFAULT NULL,
  `cm_my_tm` decimal(10,5) DEFAULT NULL,
  `cm_tm_en` decimal(10,5) DEFAULT NULL,
  `cm_tm_chn` decimal(10,5) DEFAULT NULL,
  `cm_tm_my` decimal(10,5) DEFAULT NULL,
  `cw_en_chn` decimal(10,5) DEFAULT NULL,
  `cw_en_my` decimal(10,5) DEFAULT NULL,
  `cw_en_tm` decimal(10,5) DEFAULT NULL,
  `cw_chn_en` decimal(10,5) DEFAULT NULL,
  `cw_chn_my` decimal(10,5) DEFAULT NULL,
  `cw_chn_tm` decimal(10,5) DEFAULT NULL,
  `cw_my_en` decimal(10,5) DEFAULT NULL,
  `cw_my_chn` decimal(10,5) DEFAULT NULL,
  `cw_my_tm` decimal(10,5) DEFAULT NULL,
  `cw_tm_en` decimal(10,5) DEFAULT NULL,
  `cw_tm_chn` decimal(10,5) DEFAULT NULL,
  `cw_tm_my` decimal(10,5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `similarity_st_mBERT` (
  `id` int NOT NULL,
  `translate_chn` decimal(10,5) DEFAULT NULL,
  `translate_my` decimal(10,5) DEFAULT NULL,
  `translate_tm` decimal(10,5) DEFAULT NULL,
  `cm_en_chn` decimal(10,5) DEFAULT NULL,
  `cm_en_my` decimal(10,5) DEFAULT NULL,
  `cm_en_tm` decimal(10,5) DEFAULT NULL,
  `cm_chn_en` decimal(10,5) DEFAULT NULL,
  `cm_chn_my` decimal(10,5) DEFAULT NULL,
  `cm_chn_tm` decimal(10,5) DEFAULT NULL,
  `cm_my_en` decimal(10,5) DEFAULT NULL,
  `cm_my_chn` decimal(10,5) DEFAULT NULL,
  `cm_my_tm` decimal(10,5) DEFAULT NULL,
  `cm_tm_en` decimal(10,5) DEFAULT NULL,
  `cm_tm_chn` decimal(10,5) DEFAULT NULL,
  `cm_tm_my` decimal(10,5) DEFAULT NULL,
  `cw_en_chn` decimal(10,5) DEFAULT NULL,
  `cw_en_my` decimal(10,5) DEFAULT NULL,
  `cw_en_tm` decimal(10,5) DEFAULT NULL,
  `cw_chn_en` decimal(10,5) DEFAULT NULL,
  `cw_chn_my` decimal(10,5) DEFAULT NULL,
  `cw_chn_tm` decimal(10,5) DEFAULT NULL,
  `cw_my_en` decimal(10,5) DEFAULT NULL,
  `cw_my_chn` decimal(10,5) DEFAULT NULL,
  `cw_my_tm` decimal(10,5) DEFAULT NULL,
  `cw_tm_en` decimal(10,5) DEFAULT NULL,
  `cw_tm_chn` decimal(10,5) DEFAULT NULL,
  `cw_tm_my` decimal(10,5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `similarity_st_XLMR` (
  `id` int NOT NULL,
  `translate_chn` decimal(10,5) DEFAULT NULL,
  `translate_my` decimal(10,5) DEFAULT NULL,
  `translate_tm` decimal(10,5) DEFAULT NULL,
  `cm_en_chn` decimal(10,5) DEFAULT NULL,
  `cm_en_my` decimal(10,5) DEFAULT NULL,
  `cm_en_tm` decimal(10,5) DEFAULT NULL,
  `cm_chn_en` decimal(10,5) DEFAULT NULL,
  `cm_chn_my` decimal(10,5) DEFAULT NULL,
  `cm_chn_tm` decimal(10,5) DEFAULT NULL,
  `cm_my_en` decimal(10,5) DEFAULT NULL,
  `cm_my_chn` decimal(10,5) DEFAULT NULL,
  `cm_my_tm` decimal(10,5) DEFAULT NULL,
  `cm_tm_en` decimal(10,5) DEFAULT NULL,
  `cm_tm_chn` decimal(10,5) DEFAULT NULL,
  `cm_tm_my` decimal(10,5) DEFAULT NULL,
  `cw_en_chn` decimal(10,5) DEFAULT NULL,
  `cw_en_my` decimal(10,5) DEFAULT NULL,
  `cw_en_tm` decimal(10,5) DEFAULT NULL,
  `cw_chn_en` decimal(10,5) DEFAULT NULL,
  `cw_chn_my` decimal(10,5) DEFAULT NULL,
  `cw_chn_tm` decimal(10,5) DEFAULT NULL,
  `cw_my_en` decimal(10,5) DEFAULT NULL,
  `cw_my_chn` decimal(10,5) DEFAULT NULL,
  `cw_my_tm` decimal(10,5) DEFAULT NULL,
  `cw_tm_en` decimal(10,5) DEFAULT NULL,
  `cw_tm_chn` decimal(10,5) DEFAULT NULL,
  `cw_tm_my` decimal(10,5) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;